### ISSUE TITLE
Data Access via URL, github etc

### ISSUE THREAD

**Issue by lawrennd** [lawrennd/lynguine#20]
The software currently accesses data on the local disk, but with the access.download file there's the possibility to download form other sources.

Need a format under input, output etc (i.e. to be read by config.interface) that triggers softwre to dowload before reading. E.g. something like
```
input:
  source:
    type: url
    # more details of the source here (see e.g. the data resources in https://github.com/sods/ods)
  type: yaml
```

Another possibility is that this is just another interface file where input is the source, and output is the filename. 

Other types of file access might be github, a sql server, google sheets ... the idea is that some access and potential authorization are requred before the data is availble locally. When this is present it would would trigger software to download before accessing. 

Should probably involve an:`ndlpy/access/authorize.py` file alongside the `ndlpy/access/download.py` capability.
